### ISSUE TITLE
Add rust-tools documentation to main README.md

### ISSUE THREAD

**Issue by Leo-Campo** [Leo-Campo/Dotfiles#16]
Add rust-tools entry to list of tools with some documentation in the main README

**Comment by akj2018** [comment]
Hi, I would like to work on this issue.

**Comment by Leo-Campo** [comment]
Sure! I've created a branch for this issue

**Comment by akj2018** [comment]
Is there any specific URL to be attached with Rust-Tools entry name in README.md ?

**Comment by Leo-Campo** [comment]
> Is there any specific URL to be attached with Rust-Tools entry name in README.md ? Or do you think this link works - [main/rust-tools/README.md](https://github.com/Leo-Campo/Dotfiles/tree/main/rust-tools)

I think that link is fine. I've linked other entries to their official site, but being rust-tools a collection of programs put together there's no such thing.
